### ISSUE TITLE
is it possible to operate on the current unix time as a unit?

### ISSUE THREAD

**Issue by sentriz** [nkanaev/numb#3]
for example i would like to say `(time to us) - 7 days` to mean something like `1660060569447626568 - 604800000000000`
to operate on unix microseconds

**Comment by nkanaev** [comment]
sorry for the late reply.

the underlying data that represents time is `time.Time`, which is the nanoseconds since `January 1, year 1, 00:00:00.000000000 UTC`. this, however, is not exposed in the language explicitly, because there are various digital time representations. for ex., the unix time starts in 1970, whereas UUID time represents (rather unusual) 100-nanoseconds since 1582.

i plan to add some functions to make dealing with times easier, but currently it's impossible. you could try:

```
time - {1970-01-01} to us
```

to mean the current timestamp in microseconds, but the result will be slightly off due to the timezones.
